---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ramen-gitops
  namespace: ramen-samples
spec:
  type: GitHub
  pathname: https://github.com/asn1809/ocm-ramen-samples.git
