apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  labels:
    app: deployment-rbd
  name: drpc2
  namespace: deployment-rbd
spec:
  drPolicyRef:
    name: dr-policy
  placementRef:
    kind: Placement
    name: placement2
  preferredCluster: dr1
  pvcSelector:
    matchLabels:
      appname: busybox
