apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: deployment-rbd
  name: deployment-rbd
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: workloads/deployment/k8s-regional-rbd2
  labels:
    app: deployment-rbd
  name: subscription2
  namespace: deployment-rbd
spec:
  channel: ramen-samples/ramen-gitops
  placement:
    placementRef:
      kind: Placement
      name: placement2
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: deployment-rbd
  name: placement2
  namespace: deployment-rbd
spec:
  clusterSets:
  - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: dr2
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  labels:
    app: deployment-rbd
  name: default
  namespace: deployment-rbd
spec:
  clusterSet: default
